version: '3.8'
services:
  openpcdet:
    build: 
      context: .
      dockerfile: Dockerfile
    image: openpcdet:latest
    container_name: openpcdet_container
    devices:
      - nvidia.com/gpu=all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - /home/bd/MP/datasets:/root/second.pytorch/data

    shm_size: '8gb'

    stdin_open: true
    tty: true
